apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitter-to-kafka
  name: twitter-to-kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-to-kafka
  template:
    metadata:
      labels:
        app: twitter-to-kafka
    spec:
      containers:
        - name: twitter-to-kafka
          image: zherdev/twitter-to-kafka:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: mysql
      restartPolicy: Always