scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'twitter-to-kafka-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['twitter-to-kafka-service:8181']

  - job_name: 'kafka-to-elastic-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['kafka-to-elastic-service:8182']

  - job_name: 'elastic-query-service'
    scrape_interval: 1m
    metrics_path: '/elastic-query-service/actuator/metrics'
    static_configs:
      - targets: ['elastic-query-service-1:8183']

  - job_name: 'elastic-query-web-client'
    scrape_interval: 1m
    metrics_path: '/elastic-query-web-client/actuator/metrics'
    static_configs:
      - targets: ['elastic-query-web-client:8184']

#  - job_name: 'elastic-query-service-2'
#    scrape_interval: 1m
#    metrics_path: '/actuator/metrics'
#    static_configs:
#      - targets: [ 'elastic-query-service-2:8186' ]
#  - job_name: 'kafka-streams-service'
#    scrape_interval: 1m
#    metrics_path: '/actuator/metrics'
#    static_configs:
#      - targets: ['kafka-streams-service:8187']
#  - job_name: 'analytics-service'
#    scrape_interval: 1m
#    metrics_path: '/actuator/metrics'
#    static_configs:
#      - targets: ['analytics-service:8188']